define([
  "ojL10n!lzn/gamma/resources/nls/origination-generic"
], function(Generic) {
  "use strict";

  const reviewLocale = function() {
    return {
      root: {
        compName: "review",
        beforesubmit: "Please review your information before submitting your application.",
        primaryInfo: "Personal Information",
        identityInfoTitle: "Proof of Identity",
        noCustomizationAdded: "No customizations made.",
        contactInfoTitle: "Contact Information",
        employment: "Employment Information",
        specifications: "Features and Specifications",
        accountFundingtitle: "Fund Your Account",
        depositDetailsTitle: "Deposit Details",
        title: "Financial Details",
        financialDetailsTitle: "Financial Details {index}",
        allAssets: "Assets",
        allLiabilities: "Liabilities",
        allIncome: "Incomes",
        allExpenses: "Expenses",
        edit: "Edit",
        editTitle: "Click to edit the section",
        editPersonalPrimaryInfoClick: "Person Primary information",
        editPersonalPrimaryClick: "Click For Edit Personal Info",
        editPersonalDetailsClick: "Edit Personal Information",
        editPersonalDetailsClickInfo: "Edit Personal Info",
        editPersonalFundingTable: "Edit personal funding table click",
        editPersonalFundingTableClick: "Edit personal funding table click Info",
        editPersonalInfoClick: "Click For Personal Information",
        editIdentityInfo: "Click For Identity Information",
        editIdentityInfoClick: "Click For Edit Identity Info",
        editContactInfo: "Click For Contact Information",
        editContactInfoClick: "Click For Edit Contact Info",
        editOccupationInfo: "Click For Edit Occupation",
        editOccupationInfoClick: "Click For Edit Occupation Info",
        accountHolderClick: "Click For Account Holder",
        accountHolderClickInfo: "Click For Account Holder Info",
        editAccountFundingClick: "Click For Account Funding",
        editAccountFundingClickInfo: "Click For Edit Account Funding Info",
        incomeInfoClick: "Click For Income Information",
        incomeInfoOnClick: "Click For Income Info",
        expenseInfoClick: "Click For Expense Information",
        expenseInfoOnClick: "Click For Expense Info",
        editAssetInfoClick: "Click For Edit Asset Information",
        editAssetInfoOnClick: "Click For Edit Asset Info",
        editLiabilityInfoClick: "Click For Edit Liability Info",
        editLiabilityInfoOnClick: "Click For Edit Liability Information",
        curentAssetInfoClick: "Click For Current Asset Info",
        curentAssetInfoOnClick: "Click For Current Asset Information",
        currentLiabilitiesInfoClick: "Click For Current Liability Info",
        currentLiabilityInfoClick: "Click For Current Liability Information",
        customizeCardClick: "Click For Customized Card",
        editInsuranceDetailsClick: "Click For Insurance Details",
        editCardDetailsClick: "Click For Edit Card Details",
        editCardDetailsClickInfo: "Click For Edit Card Details Info",
        cardDetailClick: "Click For Card Details",
        primaryOccupation: "Primary Employment",
        additionalOccupation: "Additional Employment",
        collateralDetailsTitle: "Collateral Details",
        accountDetails: "Savings Account Details",
        additionalPref: "Additional Preferences",
        delPreferences: "Delivery Preferences",
        addOnCardDetails: "Add-On Card Holder Details",
        disclosuresAndConsents: "Disclosures and Consents",
        cardBalanceTransfeTitle: "Balance Transfer",
        customizeYourCard: "Customize your Card",
        resAddr: "Residential Address",
        generic: Generic,
        image: "{accordionLogo} logo"
      },
      ar: true,
      fr: true,
      cs: true,
      sv: true,
      en: false,
      "en-us": false,
      el: true
    };
  };

  return new reviewLocale();
});
