define([], function() {
  "use strict";

  const OriginationLocale = function() {
    return {
      root: {
        apply: "Apply",
        add: "Add",
        addenrole: "Add Enterprise Roles",
        addedApplicationRoles: "Added Application Roles",
        addedenrole: "Added Enterprise Roles",
        addResources: "Add Resources",
        addedEntitlements: "Added Entitlements",
        addnewPolicy: "Add New Policy",
        resourceHeading: "Add New Resource",
        entitlementsHeading: "Add New Entitlement",
        approle: "Application Roles",
        appRoleCreation: "Application Role Creation",
        displayName: "Display Name",
        edit: "Edit",
        enRoleName: "Enterprise Role Name",
        ent: "Entitlements",
        entDetails: "Entitlement Details",
        enrole: "Enterprise Roles",
        entName: "Entitlement Name",
        name: "Name",
        next: "Next",
        save: "Save",
        mapApplicationRoles: "Map Application Roles",
        mapenrole: "Map Enterprise Roles",
        mapResources: "Map Resources",
        mappedResources: "Mapped Resources",
        mapEntitlements: "Map Entitlements",
        mapTransaction: "Map Transaction",
        accessPoint: "Map Transactions to Touch Points",
        accessPointTab: "Touch Point Tab",
        noAppRole: "No Application Roles Added.",
        noEnRole: "No Enterprise Roles Added",
        noEnt: "No entitlements added.",
        policy: "Policies",
        pol: "Policy",
        polName: "Policy Name",
        policyName: "Policy Name",
        policyDomains: "Policy Domains",
        polDomain: "Policy Domain",
        resource: "Resources",
        moduleName: "Module Name",
        categoryName: "Category Name",
        userSegment: "User Segment",
        accessType: "Touch Point Type",
        scopeName: "Scope Name",
        appRoleName: "Application Role Name",
        desc: "Description",
        resName: "Resource Name",
        resType: "Resource Type",
        searchAppRole: "Search Application Roles and map them with the Policy",
        searchEnRole: "Search Enterprise Roles and map them with Application Role",
        searchEnRolePolicy: "Search Enterprise Roles and map them with Policy",
        searching: "Searching...",
        searchRes: "Search for resources and add them to the entitlement",
        searchResPolicy: "Search resources and map them with the policy",
        ok: "Ok",
        completed: "Completed",
        noRecord: "No records found",
        deletedEntitlement: "Entitlement deleted successfully",
        deletedPolicyDomain: "Policy domain deleted successfully",
        deletedResource: "Resource deleted successfully",
        deletedPolicy: "Policy deleted successfully",
        deletedAppRole: "Application Role deleted successfully",
        deleteMessage: "Are you sure you want to delete this role?",
        deleteResource: "Are you sure you want to delete this resource?",
        roleTransactionMapping: "Role Transaction Mapping",
        roleTransactionMappingTransactionName: "Role Transaction Mapping",
        appRoleDetails: "Application Role Details",
        deleteHeader: "Delete",
        copyDataMessage: "Do you want to copy data from Touch Point?",
        copyDataHeader: "Copy data from Touch Point",
        addReviewHeaderMsg: "You Initiated a request for creating Role Transaction Mapping. Please review details before you confirm!",
        addResourceHeaderMsg: "You Initiated a request for updating an entitlement. Please review details before you confirm!",
        editReviewHeaderMsg: "You Initiated a request for editing Role Transaction Mapping. Please review details before you confirm!",
        cancelDisclaimer: "Are you sure you want to cancel this transaction ?",
        verticalSeperation: "|",
        userType: "User Type",
        menu: {
          internal: "Internal",
          external: "External"
        }
      },
      ar: true,
      fr: true,
      cs: true,
      sv: true,
      en: false,
es :true,
      "en-us": false,
      el: true
    };
  };

  return new OriginationLocale();
});
