define([], function() {
  "use strict";

  return new function() {
    return {
      root: {
        addMoreOptionLabel: "Add more Option",
        questionLabel: "Feedback Question",
        scaleTypeText: "Scale",
        selectOptionApplicableLable: "Please Select Applicable Options",
        nextButtonPreview: "Save and Review",
        applicableRoleLabel: "Applicable to Role",
        questionNumber: "Question {questionNumber}",
        submitButton: "Submit",
        create: "Create",
        searchWrapperTitle: "Feedback Template definition",
        templateIdLabel: "Template Id",
        templateIdPlaceholder: "Enter Template Id",
        templateNameLabel: "Template Name",
        templateNamePlaceholder: "Enter Template Name",
        titleForScale: "Scale",
        templateIdentifier: "Template Id",
        templateName: "Template Name",
        applicableToRole: "Applicable To Role",
        search: "Search",
        overallQuestion: "Please rate your overall experience",
        title: "Feedback Template Maintenance",
        questionText: "Add Another question",
        selectScale: "Select Scale",
        linkTransaction: "Link Transaction",
        selectQuestions: "Select Question",
        selectTransactionLabel: "Select Transaction",
        addAnotherTransactionLink: "Add Another Transaction",
        selectOptions: "Options",
        confirmButton: "Confirm",
        titleForQuestion: "Question",
        landingHelpTitle: "Feedback Template Definition",
        titleFortransaction: "Transaction",
        message: "Feedback Template",
        titleForTemplate: "Feedback Template",
        addOptionLabel: "Please Add Options For Question",
        addAnotherQuestionButton: "Add",
        landinghelpQuestion: "Feedback template allows definition of Feedback Question, Scale selection, Question bank along with applicable options and selection of transactions for which feedback needs to be enabled",
        helpScale: "Feedback template allows definition of Feedback Question, scale selection, question bank along with application options and selection of transactions for which feedback needs to be enabled. As part of this step, user defines the feedback question and select the applicable scale (from the pre-defined list) that will be applicable to all transactions selected in the subsequent steps.",
        createTextScale: "Scale Rating",
        createTextQuestion: "Select Question",
        createTextTransaction: "Link Transaction",
        reviewHeader: "You initiated a request for Feedback Template Maintenance. Please review details before you confirm!",
        next: "Next",
        edit: "Edit",
        save: "Save",
        cancel: "Cancel",
        clear: "Clear",
        back: "Back",
        previous: "Previous",
        createFeedback: "Feedback created Successfully",
        ok: "Ok",
        confirmation: "Confirmation",
        feedbackType: "Feedback Type",
        feedbackTypeGeneral: "General",
        feedbackTypeTransactions: "Transactions",
        optionDescription: "Option Description",
        reviewTemplate: "Review template",
        transactionSelectMessage: "Please define at least one option for the selected question",
        noQuestionMapped: "No question mapped",
        reviewCaption : "Review"
      },
      ar: true,
      fr: true,
      cs: true,
      sv: true,
      en: false,
es :true,
      "en-us": false,
      el: true
    };
  };
});
