define([], function () {
    "use strict";

    const MenuLocale = function () {
        return {
            root: {
                menu: {
                    mailboxAlt: "Mail Box",
                    mailbox: "Mail Box",
                    groups: {
                        "loan-drawdown": "Loan Drawdown Request",
                        "sweep-in-instruction": "Manage Sweep-in",
                        certificates: "Certificates",
                        "interest-certificates": "Interest Certificates",
                        "balance-certificate": "Balance Certificates",
                        "interest-certificate-casa": "Current and Savings",
                        "interest-certificate-td": "Deposits",
                        "interest-certificate-loans": "Loans",
                        "tax-deduction-at-source": "TDS",
                        "compliance-base": "Compliance",
                        "entity-compliance-base": "Entity Compliance",
                        DASHBOARD: "Dashboard",
                        ACCOUNTS_TITLE: "Accounts",
                        RECURRING_DEPOSIT_TITLE: "Recurring Deposits",
                        "rd-redeem": "Redemption",
                        "rd-calculator": "New Recurring Deposit",
                        "rd-amend": "Edit Maturity Instruction",
                        "view-statement": "View Statement",
                        redemption: "Redemption",
                        "request-statement": "Request Statement",
                        SETUP: "Setups",
                        INQUIRES: "Inquiries",
                        PAYMENTS_TITLE: "Payments",
                        "task-purpose-landing": "Payment Purpose Mapping",
                        "segment-payee-restriction-mapping": "Payee Restriction",
                        "manage-category": "Biller Category Maintenance",
                        "view-forex-deal-settings": "Forex Deal Settings",
                        "biller-category-landing": "Biller Category Maintenance - Integrated",
                        "view-network-preference": "Network Preference Maintenance",

                        CASA_ACCOUNT: "Current and Savings",
                        "casa-nominee-list": "Current and Savings",
                        "td-nominee-list": "Term Deposits",
                        "rd-nominee-list": "Recurring Deposits",
                        "apply-online": "Apply Online",
                        NEW_ACCOUNT: "New Account",
                        "application-tracking-base": "Track your application",
                        nominee: "Nominee",
                        "demand-deposits": "Overview",
                        "demand-deposit-transactions": "View Statement",
                        "term-deposit-transactions": "View Statement",
                        "recurring-deposit-transactions": "View Statement",
                        "loan-transactions": "View Statement",
                        "cheque-status-inquiry": "Cheque Status Inquiry",
                        "cheque-book-request": "Cheque Book Request",
                        "cheque-stop-unblock": "Stop/Unblock Cheque",
                        "demand-deposit-statement-request": "Request Statement",
                        "term-deposit-statement-request": "Request Statement",
                        "recurring-deposit-statement-request": "Request Statement",
                        "debit-card-list": "Debit Cards",
                        TERM_DEPOSIT_ACCOUNT: "Term Deposits",
                        "term-deposits": "Overview",
                        "td-details": "Term Deposit Details",
                        "demand-deposit-details": "Saving & Current Account Details",
                        "td-topup": "Top Up",
                        "td-open": "New Deposit",
                        "td-redeem": "Redemption",
                        "td-amend": "Edit Maturity Instruction",
                        UPI: "UPI",
                        "manage-vpa": "Manage VPA",
                        "upi-request-money": "Request Money",
                        "upi-pending-request": "Pending Requests",
                        "split-money-list": "Split Bill",
                        "transaction-history": "Transaction History",
                        "adhoc-transfer-vpa": "Fast Transfer",
                        "transfer-payee-upi": "Transfer Money",
                        "view-forex-deal": "Forex Deal",
                        LIQUIDITY_MANAGEMENT_TITLE: "Liquidity Management",
                        "liquidity-management": "Overview",
                        "create-structure": "Create Structure",
                        "view-sweep-log": "View Sweep Log",
                        "list-structure": "Structure list",
                        LOAN: "Loans and Finances",
                        loans: "Overview",
                        "loan-details": "Loan Details",
                        "loan-repayment": "Loan Repayment",
                        "loan-disbursement": "Disbursement Inquiry",
                        "loan-schedule": "Schedule Inquiry",

                        AGGREGATE_ACCOUNT: "Aggregate Accounts",
                        aggreate_accounts_list: "Register Account",

                        NOMINATIONS_TITLE: "Nominations",
                        TRADE_FINANCE: "Trade Finance",
                        "shipping-guarantee-nav-bar": "Initiate Shipping Guarantee",
                        "shipping-guarantees": "View Shipping Guarantees",
                        "shipping-guarantee": "Shipping Guarantee",
                        "letter-of-credit": "Letter Of Credit",
                        "lc-nav-bar": "Initiate LC",
                        "import-lc": "View Import LC",
                        "export-lc": "View Export LC",
                        bills: "Bills & Collection",
                        "import-bills": "View Import Bills",
                        "export-bills": "View Export Bills",
                        "list-collection": "Initiate Collection",
                        guarantee: "Guarantee",
                        "guarantee-list": "Initiate Outward Guarantee",
                        "outward-guarantees": "View Outward Guarantee",
                        "inward-guarantees": "View Inward Guarantee",
                        "customer-acceptance-nav-bar": "Customer Acceptance",
                        "customer-acceptance-lc-base": "LC Amendments",
                        "customer-acceptance-bills-base": "Bill Discrepancies",
                        "customer-acceptance-guarantee-base": "Guarantee Amendments",
                        "search-beneficiary-maintenance": "Beneficiary Maintenance",
                        "search-credit-line": "Line Limits Utilization",
                        PAYMENTS_OVERVIEW: "Overview",
                        "payee-list": "Manage Payees",
                        "biller-list": "Manage Billers",
                        "manage-payees-billers": "Manage Payees",
                        "standing-instructions-list": "Repeat Transfers",
                        "standing-instructions-landing": "Repeat Transfers",
                        "bill-payments": "Pay Bills",
                        "payments-money-transfer": "Transfer Money",
                        "payments-transfers": "Payments and Transfers",
                        "adhoc-payments": "Fast Payment",
                        "multiple-payments": "Multiple Transfers",
                        "multiple-bill-payments": "Multiple Bill Payments",
                        "adhoc-draft": "Adhoc Demand Draft",
                        "issue-demand-draft": "Issue Demand Drafts",
                        "debtor-money-request": "Request Money",
                        "debtor-group-list": "Manage Debtors",
                        "fund-transfer-history": "Funds Transfer History",
                        "scheduled-payments": "Upcoming Payments Inquiry",
                        "inward-remittance": "Inward Remittance Inquiry",
                        "outward-remittance": "Outward Remittance Inquiry",
                        "requested-funds-summary": "Requested Funds Summary",
                        "add-money-to-wallet": "Add Money To Wallet",
                        favorites: "Favorites",
                        CREDIT_CARD_TITLE: "Credit Cards",
                        CC_OVERVIEW: "Overview",
                        "card-details": "Credit Card Details",
                        "card-statement": "View Statement",
                        "card-pay": "Card Payment",
                        "request-pin": "Request PIN",
                        "block-card": "Block/Cancel Card",
                        "auto-pay": "Auto Pay",
                        "creditcard-reset-pin": "Reset PIN",
                        "add-on-card": "Add-On Card",
                        MAILBOX_TITLE: "Mail Box",
                        PERSONAL_FINANCE_MANAGEMENT: "Personal Financial Management",
                        "spend-category-landing": "Spend Category Maintenance",
                        "goal-category-list": "Goal Category Maintenance",
                        "add-ext-bank": "External Bank Maintenance",
                        "list-budget": "Budget",
                        "list-goal": "Goal List",
                        "goal-category-selection": "New Goal",
                        GOAL: "Goal",
                        SPEND: "Spend",
                        "manage-spend-categories": "Manage Categories",
                        "transaction-list": "View Transactions",
                        "mailbox-base": "Mails",
                        "alert-list": "Alerts",
                        "notification-list": "Notification",
                        FILE_UPLOAD: "File Upload",
                        ACCESS_POLICIES: "Authorization and Access Controls",
                        "access-point-search": "Touch Points",
                        "access-point-group-search": "Touch Points Group",
                        "application-role-base": "Role Transaction Mapping",
                        "entitlements-base": "Entitlements",
                        "search-segments": "User Segments Definition",
                        "file-identifier-search": "File Identifier Maintenance",
                        "user-search": "User File Identifier Mapping",
                        "file-create": "File Identifier Maintenance",
                        "user-search-type": "User File Identifier Mapping",
                        "file-upload": "File Upload",
                        "file-view": "Uploaded Files Inquiry",
                        VIRTUAL_ACCOUNT_MANAGEMENT_TITLE: "Virtual Account Management",
                        "virtual-account-management": "Overview",
                        "virtual-entity": "Virtual Entity",
                        "virtual-entity-landing": "Virtual Entity",
                        "virtual-account-landing": "Virtual Accounts",
                        "virtual-account-main": "Virtual Account",
                        "remitter-list": "Remitter List",
                        "virtual-entity-search": "View/Edit Virtual Entity",
                        "virtual-entity-create": "Create Virtual Entity",
                        "virtual-account-search": "View/Edit Virtual Account",
                        "virtual-account": "Create Virtual Account",
                        "virtual-structure-search": "View/Edit Structure",
                        "virtual-structure": "Virtual Accounts Structure",
                        "remittance-search": "View/Edit Remitter List",
                        "virtual-identifiers-create": "Create Remitter List",
                        "virtual-account-structure-create": "Create Structure",
                        "virtual-multi-currency-account-main": "Virtual Multi-Currency Account",
                        "virtual-multi-currency-account": "Create Virtual Multi-Currency Account",
                        "virtual-multi-currency-account-search": "View/Edit Virtual Multi-Currency Account",
                        "create-move-money": "Move Money",
                        "virtual-account-statement": "Virtual Account Statement",
                        PARTY_TO_PARTY_LINKAGE: "Party To Party Linkage",
                        ON_BOARDING: "Onboarding",
                        "biller-search": "Biller Onboarding",
                        COMMUNICATION: "Communication",
                        "mapping-base": "User Group Subject Mapping",
                        "mailers-base": "Mailers",
                        CONTROLS_AND_MONITORING: "Controls and Monitoring",
                        USER_EXPERIENCE: "User Experience",
                        TEMPLATES: "Templates",
                        CONFIGURATION: "Configuration",
                        "system-configuration-home": "System Configuration",
                        "system-rules-map": "System Rules",
                        "task-aspects": "Transaction Aspects",
                        "location-search": "Branch Maintenance",
                        "user-segments-product-list": "Product Mapping",
                        "profile-maintenance-search": "User Profile Maintenance",
                        OAUTH: "OAuth",
                        "resource-server-search": "Resource Server Maintenance",
                        "identity-domain-search": "Identity Domain Maintenance",
                        "client-search": "Client Maintenance",
                        USER_MANAGEMENT: "User Management",
                        CORPORATE_PREFERENCES: "Party Preferences",
                        LIMITS: "Limits",
                        "limit-search": "Limit Definition",
                        "limit-package-search": "Limits Package",
                        "transaction-group-search": "Transaction Group Maintenance",
                        APPROVALS: "Approvals",
                        "workflow-type": "Workflow Management",
                        "rule-type": "Rules Management",
                        workflow: "Workflow Management",
                        rules: "Rules Management",
                        "user-group-type": "User Group Management",
                        ACCESS_MANAGEMENT: "Access Management",
                        ACCOUNT_ACCESS: "Account Access",
                        RESOURCE_ACCESS: "Resource Access",
                        "access-management-base": "Party Account Access",
                        "party-base": "Party Resource Access",
                        "user-base": "User Resource Access",
                        SERVICE_REQUEST_CONFIG: "Service Requests",
                        "service-requests-menu": "Service Request",
                        "service-requests-track": "Track Request",
                        "service-requests-base": "Request Processing",
                        "dashboard-create": "Personalize Dashboard",
                        "view-dashboard-design": "Personalize Dashboard",
                        "feedback-capture": "Leave Feedback",
                        "feedback-template-search": "Feedback Template",
                        "sms-banking-search": "SMS and Missed Call Banking",
                        "relationship-mapping-base": "Relationship Mapping",
                        "relationship-matrix-base": "Relationship Matrix",
                        "transaction-blackout": "Transaction Blackout",
                        "service-requests-base-main": "Raise New Request",
                        "user-access-management-base": "User Account Access",
                        "manage-service-request": "Manage Service Requests",
                        SUPPLY_CHAIN_FINANCE: "Supply Chain Finance",
                        PROGRAM_MANAGEMENT: "Program Management",
                        "supply-chain-finance": "Overview",
                        "program-management-global": "Create Program",
                        "invoice-accept-reject": "Accept/Reject Invoice",
                        "select-role": "View/Edit Program",
                        INVOICE_MANAGEMENT: "Invoice Management",
                        "invoice-creation-home": "Create Invoice",
                        "select-role-invoice": "View/Edit Invoice",
                        ASSOCIATED_PARTY_MANAGEMENT: "Associated Party Management",
                        "onboard-counter-party-form": "Onboard Counterparty",
                        "counter-party-list": "View Associated Parties",
                        FINANCE_MANAGEMENT: "Finance Management",
                        "request-finance-global": "Request Finance",
                        "view-finances": "View Finances",
                        WEALTH_MANAGEMENT: "Wealth Management",
                        "mutual-funds": "Overview",
                        START_INVESTING: "Start Investing",
                        PLACE_ORDERS: "Place Orders",
                        REPORTS: "Reports",
                        "purchase-mutual-fund-train": "Purchase Mutual Fund",
                        "risk-profile-account-selection": "Risk Profiling",
                        "redeem-funds-global": "Redeem Mutual Fund",
                        "order-status": "Order Status",
                        "capital-gain-reports": "Capital Gains Report",
                        "dividend-reports": "Dividends Report",
                        "transaction-reports": "Transactions Report",
                        "switch-funds-global": "Switch Mutual Fund",
                        "investment-details-dashboard": "Investment Details",
                        "open-investment-account-landing": "Open Investment Account",
                        "report-generation": "Report Generation",
                        "report-list": "My Reports",
                        "reports-type": "User Report Mapping",
                        "audit-log": "Audit Log",
                        OTHERS: "Others",
                        "transaction-cutoff": "Working Window",
                        "help-desk-user-search": "User Help Desk",
                        "application-message-list": "Message Maintenance",
                        SECURITY: "Security",
                        "segment-authentication-mapping": "Authentication",
                        "view-security-question-maintenance": "Manage Security Questions",
                        "policy-search": "Password Policy Maintenance",
                        "alerts-maintenance-search": "Alert Maintenance",
                        "manage-alerts-subscription": "Manage Alerts",
                        "alerts-select-user": "Alert Subscription",
                        "claim-payment-dashboard": "Claim Money",
                        "track-application": "Track Application",
                        "user-credentials": "Register",
                        "service-requests-search": "Service Request-Form Builder",
                        "security-keys": "Security Keys",
                        origination: "Workflow Configuration",
                        login: "Login",
                        logout: "Logout",
                        clickhere: "Click to view {name}",
                        locator: "Branch Locator",
                        "preference-base": "Party Preferences",
                        users: "User Management",
                        "linkage-base": "Party To Party Linkage",
                        profile: "My Profile",
                        "template-list": "Dashboard Builder",
                        "theme-list": "Manage Brand",
                        ACCOUNT_SETTING: "Account Setting",
                        "session-summary": "Session Summary",
                        "alerts-list": "Manage Alerts",
                        "list-user": "User Limits",
                        "my-limits": "My Limits",
                        "view-user-security-question": "Set Security Question",
                        "change-password": "Change Password",
                        "print-user-search": "Print Password",
                        "security-menu": "Security Settings",
                        help: "Service",
                        about: "Contact Us",
                        "third-party-consents": "Manage Third Party Consents",
                        "feedback-analysis": "Feedback Analytics",
                        BILL_PAYMENTS_TITLE: "Bill Payments",
                        API_BUILDER: "API Builder",
                        "api-group-search": "Group Builder",
                        "api-builder-search": "Service Builder",
                        "bill-payments-favorites": "Favorites",
                        "manage-bill-payments": "Bills",
                        "register-biller": "Add Biller",
                        "modify-biller": "Manage Billers",
                        "quick-bill-payment": "Quick Bill Pay",
                        "quick-recharge": "Quick Recharge",
                        "payment-history": "Payment History",
                        "side-menu": "My Preference",
                        ACCOUNT_SETTINGS: "Account Settings",
                        trends: "Trends",
                        "link-account-dashboard": "FuturaMax",
                        "merchant-dashboard": "Merchant Management",
                        "facility-collateral-management": "Credit Facility Management",
                        "credit-facility": "Overview",
                        "credit-facility-title": "Credit Facility",
                        "facility-overview": "Facility Summary",
                        "facility-details": "Facility Details",
                        "choose-facility-option": "Amend Facility",
                        "choose-sub-facility-option": "Apply for Sub Facility",
                        "apply-new-facility-landing": "Apply for New Facility",
                        collaterals: "Collaterals",
                        "collateral-overview": "Collateral Summary",
                        "collateral-details": "Collateral Details",
                        "collateral-evaluation-landing": "Collateral Evaluation",
                        "collateral-revaluation-flow": "Collateral Revaluation",
                        "workflow-base": "Origination Workflow Configuration",
                        "application-tracker-film-strip": "Application Tracker",
                        "td-calculator":"Terml deposit Calculator",
                        "loan-calculator":"Loan Calculator",
                        "loan-eligibility-calculator":"Loan Eligibility Calculator",
                        "forex-calculator":"Foreign Exchange Calculator"
                    }
                },
                welcome: "Welcome {firstName} {lastName}",
                lastLogin: "Your last login was on {lastLoginDate}",
                changeLanguage: "Click to change current language",
                selectLanguage: "Select Language"
            },
            ar: true,
            fr: true,
            cs: true,
            sv: true,
            en: false,
            "en-us": false,
            el: true
        };
    };

    return new MenuLocale();
});