define(["ojL10n!resources/nls/generic"], function (Generic) {
    "use strict";

    const RecordViewLocale = function () {
        return {
            root: {
                recordView: {
                    uploadedFiles: "Uploaded Files Inquiry",
                    recordView: "Record View",
                    userRefNo: "User Ref No",
                    recordDetails: "Record Details",
                    fileName: "File Name",
                    recordRefNo: "Record Ref No",
                    txnRefId: "Transaction Reference Id",
                    purposeOfRemit: "Purpose Of Remittance",
                    beneName: "Payee Name",
                    status: "Status",
                    fileView: "File View",
                    internalPayments: "Internal Payments",
                    domesticPayments: "Domestic Payments",
                    internationalPayments: "International Payments",
                    creditAccNo: "Credit Account Number",
                    creditAccBranch: "Credit Account Branch",
                    debitNarrative: "Debit Narrative",
                    creditNarrative: "Credit Narrative",
                    valueDate: "Value Date",
                    rStatus: "Record Status",
                    errorDetail: "Error Detail",
                    creditDetails: "Credit Details",
                    debitDetails: "Debit Details",
                    debitPartyId: "Debit Party Id",
                    mode: "Mode",
                    adhoc: "Adhoc",
                    partyId: "Party Id",
                    debitAccountNumber: "Debit Account No",
                    debitAccBranch: "Debit Account Branch",
                    debitCurrency: "Debit Account Currency",
                    paymentAmount: "Payment Amount",
                    paymentCurrency: "Payment Currency",
                    paymentDate: "Payment Date",
                    paymentMode: "Payment Mode",
                    clearingCode: "Clearing Code",
                    purposeOfPayment: "Purpose Of Payment",
                    bicNccCode: "BIC | NCC Code",
                    uetr: "Unique End to End Transaction Reference No",
                    paymentDetails1: "Payment Details 1",
                    paymentDetails2: "Payment Details 2",
                    paymentDetails3: "Payment Details 3",
                    paymentDetails4: "Payment Details 4",
                    payeeAddr1: "Payee Address Line 1",
                    payeeAddr2: "Payee Address Line 2",
                    payeeCity: "Payee City",
                    payeeCountry: "Payee Country",
                    valueDt: "Value Date",
                    charges: "Charges",
                    creditAccountNumber: "Credit Account No",
                    back: "Back",
                    delete: "Delete",
                    yes: "Yes",
                    no: "No",
                    deleteConfirmationMessage: "Are you sure you want to delete this record?",
                    warning: "Warning",
                    transactionName: "Record Deletion",
                    intmdDetails: "Intermediary Bank Details",
                    intmdBankName: "Intermediary Bank Name",
                    intmdAddrLine: "Intermediary Bank Address",
                    intmdCity: "Intermediary Bank City",
                    intmdCountry: "Intermediary Bank Country",
                    ultBankName: "Bank Name",
                    ultAddrLine: "Bank Address",
                    ultCity: "Bank City",
                    ultCountry: "Bank Country",
                    externalReferenceId: "External Reference ID",
                    invoiceDetails: "Invoice Details",
                    invoiceNumber: "Invoice Number",
                    invoiceDate: "Invoice Date",
                    invoiceDueDate: "Invoice Due Date",
                    invoiceAmount: "Invoice Amount",
                    supplierName: "Supplier Name",
                    buyerName: "Buyer Name",
                    programId: "Program Code",
                    programName: "Program Name",
                    taxPercentage: "Tax Percentage",
                    taxAmount: "Tax Amount",
                    discountPercentage: "Discount Percentage",
                    discountAmount: "Discount Amount",
                    totalInvoiceAmount: "Total Invoice Amount",
                    purchaseOrderNo: "Purchase Order Number",
                    preAccepted: "Pre Accepted",
                    paymentTerms: "Payment Terms",
                    purchaseOrderDate: "Purchase Order Date",
                    shipmentDate: "Shipment Date"
                },
                generic: Generic
            },
            ar: true,
            fr: true,
            cs: true,
            sv: true,
            en: false,
es :true,
            "en-us": false,
            el: true
        };
    };

    return new RecordViewLocale();
});