define([], function() {
  "use strict";

  return new function() {
    return {
      root: {
        title: "Remitter ID",
        reviewHeaderMsg: "You Created a Remitter. Please review details before you confirm!",
        reviewCaption: "Review",
        bannerMessage: "You initiated a request to modify an existing Remitter ID. Please review details before you confirm!",
        edit: "Edit",
        back: "Back",
        cancel: "Cancel",
        ok: "Ok",
        askForDelete: "Are you sure you want to delete this Remitter ID?",
        delete: "Delete",
        confirm: "Confirm",
        deleteConfirm: "Remitter delete",
        remitterListHeader: "Remitter ID",
        remitterListIdHeader: "Remitter List ID",
        remitterListIdNameHeader: "Remitter List Name",
        remitterID: "Remitter ID",
        from: "Valid From",
        to: "Valid To",
        reconciliationInformation: "Reconciliation Information",
        additionalInformation: "Additional Information",
        virtualAccountInformation: "Virtual Account information",
        entityID: "Entity ID",
        productlabel: "Product",
        currencyLabel: "Currency",
        realAccountNumber: "Real Account Number",
        interestCalReq: "Interest Calculation Required",
        accountName: "Name",
        balAvailabilityOptionsLabel: "Balance Availability Option",
        purpose: "Purpose",
        fixedAmountFromPool: "Fixed Amount From Pool",
        ownBalance: "Own Balance",
        poorBalance: "Pool Balance",
        fixedOwnBalance: "Fixed amount from pool balance",
        correspondenceAddress: "Correspondence Address",
        preferences: "Preferences",
        ibanRequired: "IBAN Required",
        balanceCheckForDebit: "Balance Check For Debits",
        debitTransactionAllowed: "Debit Transaction Allowed",
        creditTransactionAllowed: "Credit Transaction Allowed",
        linktoRealAccount: "Link this account to real a account",
        addressText: "Same as Entity Address",
        addressLine1: "Address Line 1",
        addressLine2: "Address Line 2",
        address: "Address",
        city: "City",
        creationDate: "Creation Date",
        fixedAmount: "Fixed Amount",
        overdraftOption: "Overdraft Option",
        country: "Country",
        yes: "Yes",
        no: "No",
        save: "Save",
        accountNo: "Virtual Account Number",
        status: "Status",
        active: "Active",
        inactive: "Inactive",
        close: "Closed",
        open: "Open",
        pinCode: "Pin Code",
        tips: "Note",
        successMessage: "Remitter ID deleted successfully.",
        clickToUploadFile: "Click here to bulk file upload option",
        helpInfo: "Remitter IDs are virtual accounts that do not have account balances of their own but act like pipelines to the real accounts and help to keep track of Remittance",
        updateSuccessMessage: "Remitter ID updated successfully.",
        deleteSuccessMessage: "Remitter ID deleted successfully.",
        remittanceListId: "Remitter List ID",
        remittanceName: "Remitter  Name",
        remittanceActionCardText: "Create More Remitter ID List",
        goToOverview: "Go To Overview",
        dateValidityErrorMessage: "Validity Start Date should be less than or equal to End Date"
      },
      ar: true,
      fr: true,
      cs: true,
      sv: true,
      en: false,
es :true,
      "en-us": false,
      el: true
    };
  };
});
