define([
  "ojL10n!resources/nls/account-activity",
  "ojL10n!resources/nls/generic"
], function(Activity, Generic) {
  "use strict";

  const LimitsLocale = function() {
    return {
      root: {
        pageTitle: {},
        limitsInquiry: {
          limits: "{taskName} Limits",
          header: {
            myLimits: "Limits",
            userLimits: "User Limits"
          },
          buttons: {
            updateLimit: "Update Limit",
            resetLimit: "Reset To Bank Limits",
            resetDailyLimit: "Reset Daily Field",
            resetMonthlyLimit: "Reset Monthly Field",
            editLimits: "Edit",
            showGroupInformation: "Show Group Information",
            next: "Next"
          },
          messages: {
            navBarDescription: "Navigation Bar to select action",
            header_title: "User Limit",
            remaining: "Remaining",
            utilised: "Utilized",
            analysis_title: "My Limits",
            party_limit: "Corporate Limits",
            minimum_amount_label: "Min Amount :",
            maximum_amount_label: "Max Amount :",
            total_amount: "Total - {totalamount}",
            total_count: "Total - {totalcount}",
            totalAmount: "Total",
            available_amount: "Available - {amount}",
            available_count: "Available - {count}",
            UtilizedCount: "Utilized - {count}",
            countUtilizationStatus: "Count Utilization Status",
            amountUtilizationStatus: "Amount Utilization Status",
            transaction_undefined: "Na",
            duration_undefined: "Na",
            count: "Count",
            amount: "Amount",
            limits: "Limit",
            dailyCount: "Daily Count",
            dailyAmount: "Daily Amount",
            monthlyCount: "Monthly Count",
            monthlyAmount: "Monthly Amount",
            initiationlimit: "Initiation Limit",
            perTxnLimit: "Per Transaction Limit",
            cumuDailyLimit: "Cumulative Daily Limit",
            approvallimit: "Approval Limit",
            transaction: "Transaction",
            tableheader: "User Limits Inquiry",
            newMaxLimt: "New Max Limit",
            saveMessage: "Changes will be updated on {date}. Do you want to proceed?",
            saveMessageEffective: "Are you sure you want to submit the changes?",
            confirmMessage: "Any changes made will be effective from {date}",
            validFormatAmount: "Total Cumulative Amount for the day cannot exceed the defined bank limit.",
            validFormatCount: "Total Cumulative Count for the day cannot exceed the defined bank limit.",
            validFormatAmountMonthly: "Total Cumulative Amount for the month cannot exceed the defined bank limit.",
            validFormatCountMonthly: "Total Cumulative Count for the month cannot exceed the defined bank limit.",
            validFractionalCount: "Count cannot be fractional",
            emptyCheck: "Please save all the changes before submitting.",
            willBeEffective: "The changes you made today will be effective from {date}",
            tomorrowCount: "Count : {count}",
            tomorrowAmount: "Amount : {amount}",
            viewFutureLinkage: "Changes have been made today.",
            view: "View",
            updatedSuccessfullyMsg: "Limits Updated Successfully",
            confirmHeader: "Confirmation Warning",
            bankAllocatedLimits: "Allocated by Bank :",
            bankAllocatedCounts: "Allocated by Bank :",
            periodicLabel: "{periodicity} {label}",
            countValidationMessage: "Please enter valid count",
            noDataFoundMassage: "Currently, no transaction limits are assigned in a package mapped.",
            transactions: "Transactions",
            please_select: "Please select",
            channel: "Channel",
            channelTransactionGroupLimits: "Channel & Transaction Group Limits",
            channelGroupLimits: "Channel Group Limits",
            transactionGroupLimits: "Transaction Group Limits",
            showInformation: "Select channel to view its limits",
            editLimitMessage: "Click here to edit limits",
            maxAmount: "Max Amount:",
            minAmount: "Min Amount:",
            dailyLimits: "Daily Limits",
            monthlyLimits: "Monthly Limits",
            available: "Available",
            utilized: "Utilized",
            total: "Total",
            noMonthlyLimitsAssigned: "Monthly limit package is not assigned for the selected transaction for {accessPoint} Touch Point",
            noDailyLimitsAssigned: "Daily limit package is not assigned for the selected transaction for {accessPoint} Touch Point",
            enterCount: "Enter Count",
            enterAmount: "Enter Amount",
            editLimits: "Edit Limits",
            nolimits: "Currently no limits are assigned to this transaction.\nPlease contact administrator for further details.",
            transactionGroupDetails: "Transaction Group Details",
            channelGroupDetails: "Channel Group Details",
            transactionGroup: "Click here to view Transaction Group information.",
            channelGroup: "Click here to view Channel Group information",
            labelGraph: "%\nUtilized",
            noChangesMade: "No Changes have been made in the limits.",
            limitsUpdated: "Limits updated successfully.",
            utilizedPieChart: "{utilized} Utilized of {total}",
            availablePieChart: "{available} Available of {total}",
            groupNameMessage: "Group Name :",
            groupListMessage: "Group Content :",
            groupInfo: "Group Information",
            current: "Current Limit:",
            consolidateLimits: "Consolidated Limits",
            consolidateTransactionGroupLimits: "Consolidated & Transaction Group Limits",
            expiryDate: "Expiry Date"
          }
        },
        accountActivity: Activity,
        generic: Generic
      },
      ar: true,
      fr: true,
      cs: true,
      sv: true,
      en: false,
es :true,
      "en-us": false,
      el: true
    };
  };

  return new LimitsLocale();
});
