define([], function () {
  "use strict";

  return new function () {
    return {
      root: {
        title: "Virtual Entity",
        infoPanelText: "Virtual entities are created to reflect the real legal entities such that virtual accounts & structures can also match the real entities & accounts",
        entityIDName: "Virtual Entity ID & Name",
        entityInformation: "Virtual Entity Information",
        otherDetails: "Other Details",
        preferences: "Preferences",
        entityType: "Virtual Entity Type",
        corporate: "Corporate",
        individual: "Individual",
        entityID: "Virtual Entity ID",
        entityName: "Virtual Entity Name",
        corporateType: "Corporate Type",
        dateOfBirth: "Date Of Birth",
        dateOfIncorporation: "Date Of Incorporation",
        gender: "Gender",
        countryOfIncorporation: "Country Of Incorporation",
        nationality: "Nationality",
        uniqueID: "Unique ID",
        nationalID: "National ID",
        landline: "Landline",
        addLandline: "Add Landline",
        homePhone: "Home Phone",
        workPhone: "Work Phone",
        addWorkPhone: "Add Work Phone",
        mobile: "Mobile",
        emailID: "Email ID",
        preferredMode: "Preferred Mode",
        entityAddressText: "Same as Real Entity",
        correspondenceText: "Registered Address",
        email: "Email",
        address: "Address",
        city: "City",
        country: "Country",
        zipCode: "Pin Code",
        mailingAddress: "Correspondence Address",
        addressText: "Same as Registered Address",
        addressLine1: "Address Line 1",
        addressLine2: "Address Line 2",
        tips: "Note",
        info: "Info",
        note: "Note",
        clickToUploadFile: "Click here to upload file.",
        reviewHeader: "You initiated a request to create a Virtual Entity. Please review details before you confirm!",
        viewHeader: "You initiated a request to modify a Virtual Entity. Please review details before you confirm!",
        createNewEntity: "Create New Entity",
        availableBalance: "Available Balance",
        creationDate: "Creation Date",
        childAccounts: "Child Accounts",
        consolidated: "Consolidated",
        accountLevel: "Account Level",
        askForDelete: "Are you sure you want to delete this Virtual Entity?",
        zeroBalanceError: "Balance of all the linked Virtual accounts should be zero to delete this Entity.",
        status: "Status",
        error: "Error",
        entityCreateMessage: "Virtual Entity created Successfully!",
        entityUpdateMessage: "Virtual Entity updated Successfully!",
        entityDeleteMessage: "Virtual Entity deleted Successfully!",
        goToDashboard: "Go to Dashboard",
        virtualEntityCardText: "Create Virtual Entities",
        virtualAccountCardText: "Create Virtual Accounts",
        yes: "Yes",
        no: "No",
        next: "Next",
        edit: "Edit",
        save: "Save",
        cancel: "Cancel",
        back: "Back",
        ok: "Ok",
        confirmation: "Confirmation",
        confirm: "Confirm",
        search: "Search",
        delete: "Delete",
        reset: "Reset",
        active: "Active",
        closed: "Closed",
        entityExists: "Virtual Entity ID already exists."
      },
      ar: !1,
      fr: !0,
      cs: !1,
      sv: !1,
      en: !1,
      "en-us": !1,
      el: !1
    };
  };
});