define([
  "ojL10n!lzn/beta/resources/nls/origination-generic"
], function(Generic) {
  "use strict";

  const depositRequirementsLocale = function() {
    return {
      root: {
        compName: "disclosures",
        disclosureInfo: "Please go through the following disclosures thoroughly. They contain important information about your legal rights. Copies of all disclosures will be sent to you at {emailId} once you consent to E-sign Disclosure.",
        coAppdisclosureInfo: "Please go through the following disclosures thoroughly. They contain important information about your legal rights. Copies of all disclosures will be sent to you at {emailId} and {coAppEmailId} once you consent to E-sign Disclosure.",
        eSignInfo1: "We are bound by specific laws that require us to provide certain application and account information to you. Your consent to the E-SIGN disclosure gives us the permission to provide information to you electronically and covers all subsequent disclosures, notices and communications regarding your application as well as the resulting account.",
        eSignInfo2: "When you consent to our E-SIGN Disclosure, you agree that we will deliver communications to you in electronic format by posting them on the banking website or also through Email. All electronic communication intended to be sent through Email will be sent to the Email address provided in your application.",
        eSignInfo3: "Please review the terms and conditions of our E-SIGN Disclosure and indicate your consent to receive electronic disclosures and agreements. If you do not wish to receive these documents electronically, you may cancel this application by clicking on the Cancel button at the bottom of this page.",
        eSignTitle: "E-SIGN Disclosure",
        eSignConsent: "I have reviewed and consent to the E-SIGN Disclosure.",
        wirelessPolicy: "Wireless Policy - How we will contact you",
        wirelessPolicy1: "We may contact you about your application or also our services and promotions by calling you at any number provided in your application, including your cell phone. You acknowledge that you may be charged by your wireless provider in order to receive text messages.",
        wirelessPolicyConsent: "I agree to receive communications via phone and text.",
        privacyPolicy: "Privacy Policy",
        privacyPolicy1: "Federal law also requires us to tell you how we collect, share and protect your personal information. Please read the notice carefully in order to understand our privacy policy.",
        privacyPolicyConsent: "I confirm that I have read the above disclosure.",
        loanAccountAgreement: "Loan Account Agreement",
        loanAgreement: "Loan Agreement",
        loanAgreement1: "Please review the loan agreement document. This loan agreement contains a binding Jury Trial Waiver And Arbitration Clause.",
        loanAgreement2: "Select the link to view the loan agreement. You can also print or save copies for your records. Provide consent to the agreement in order to proceed with application submission.",
        loanAgreementConsent: "I confirm that I have read the above disclosure and agree to be bound by the terms of the agreement.",
        promiseToPay: "Promise to Pay",
        promiseToPay1: "You agree to authorize the creditor to initiate an electronic debit under the ACH Authorization of the total payment due on the Due Date as mentioned below. We agree to hold and defer our right to initiate the ACH Authorization until the Due Date. Your ACH Authorization is payment to your obligations under this Loan Agreement. On the Due Date or thereafter, we initiate an electronic debit from your account.",
        equalCreditOpportunity: "Equal Credit opportunity Act",
        equalCreditOpportunity1: "The Equal Credit Opportunity Act prohibits creditors from discriminating against credit applicants on the basis of race, color, religion, national origin, sex, marital status, age (provided the applicant has the capacity to enter into a binding contract) or because all or part of the applicant's income derives from any public assistance program or because the applicant has exercised any right under the Consumer Credit Protection Act.",
        addlnDisclosures: "Additional Disclosures",
        addlnDisclosures1: "All the information I have submitted in the application, is to the best of my knowledge, true and correct.",
        addlnDisclosures2: "I am the person named in the application.",
        addlnDisclosures3: "This application and any supporting documents remain the property of the creditor.",
        addlnDisclosures4: "All loan applications are subject to normal credit qualification and the financial institute is not obligated to approve my application. I authorize the financial institute to obtain a credit report or any other report or account information from credit or information services agencies to help verify my information provided in this application.",
        addlnDisclosures5: "Credit approval, Annual Percentage Rate (APR) and credit terms are based on the review of each applicant's information and credit report.",
        acceptance: "I accept all the statements defined above.",
        TINtitle: "TIN Certification and Backup WithHolding",
        penalty: "Under penalties of perjury, I certify that",
        perjuryInfo1: "1. The number provided on this application is my correct taxpayer identification number,",
        perjuryInfo2: "2. I am not subject to backup withholding because: (a) I am exempt from backup withholding, or (b) I have not been notified by the Internal Revenue Service (IRS) that I am subject to backup withholding as a result of a failure to report all interest or dividends, or (c) the IRS has notified me that I am no longer subject to backup withholding, and,",
        perjuryInfo3: "3. I am a <a href='#' class='link' >U.S. person</a>",
        perjuryInfo4: "4. I am exempt from <a href='#' class='link' >FATCA reporting</a>",
        perjuryInfo5: "FATCA reporting",
        perjuryInfo6: "U.S. person",
        eSignatureClick: "Click For Signature",
        eSignatureDownloadClick: "Click For Download signature",
        accountDocRefIdClick: "Click For Doc ID",
        accountDocRefIdOnClick: "Click For Account Doc ID",
        accountRefIdClick: "Click For Account id",
        accountForRefIdClick: "Click For Account ref Id",
        disclosureAccountDocRefIdClick: "Click For Account Doc ID",
        privacyDocRefIdClick: "Click For Privacy Reference ID",
        privacyDocRefIdOnClick: "Click For Privacy Doc Reference ID",
        USPersonRequirementClick: "Click For USA Person",
        USPersonRequireClick: "Click For USA Person Requirement",
        USAlienRequirementClick: "Click For USA Alien",
        USAlienRequireClick: "Click For USA Aliens",
        FATCAClick: "Click For FATCA",
        FATCAOnClick: "Click For FATCA",
        perjuryInfo7: "U.S. resident alien",
        perjuryInfo8: "(including a <a href='#' class='link' >U.S. resident alien</a>)",
        perjuryNote: "Please note: If you are unable to certify that you are no subject to backup withholding, you cannot apply online.",
        perjuryNote1: "Please visit us at a banking center near you and we will help you with your application.",
        TINconsent: "I certify and under penalty of perjury, that all four tax status certification statements above are true.",
        addlnNote: "Please review important deposit product disclosures and our privacy policy. Select the links to review each item and print or save copies for your records.",
        depositAccntAgreement: "Deposit Account Agreement",
        accntAgreement: "Account Agreement",
        consumerNotice: "Consumer Privacy Notice",
        privacyConsent: "I acknowledge that I have received and agree to the Deposit Product Legal Documents and the Privacy Policy Notice",
        agreeConsent: "By clicking submit I agree that I am the person named in the application and all the information including information of co-applicants, if any, in the application is, to the best of my knowledge, correct. I also authorize Bank Name to obtain a credit report or any other report or account information from credit or information services agencies to help verify my information provided in this application.",
        usPersonDiscl: "For federal tax purposes, you are considered a U.S. person if you are: An individual who is a U.S. citizen or a U.S. resident alien, A partnership, corporation, company, or association created or organized in the United States or under the laws of the United States, An estate (other than a foreign estate), or A domestic trust (as defined in Regulations section 301.7701-7).",
        usAlienDiscl: "For federal tax purposes, you are considered a U.S. Resident Alien if you are foreign person who is a permanent resident of the United States of America and have a current green card or have had one in the previous calendar year.",
        fatcaDiscl: "As per the Foreign Account Tax Compliance Act (FATCA), all U.S. citizens (including those living abroad) and U.S. resident aliens are required to report income generated from foreign assets exceeding specific reporting thresholds, including any foreign financial accounts.",
        primaryApplicant: "Primary Applicant",
        jointApplicant: "Joint Applicant",
        messages: {
          eSignAlert: "Please accept E-Sign Disclosure",
          TINAlert: "Please acknowledge tax certification statements",
          privacyAlert: "Please acknowledge privacy policy notice",
          loanAgreement: "Please accept Loan Agreement",
          wirelessAgreement: "Please accept Wireless Agreement",
          acceptAll: "Please accept above statements"
        },
        generic: Generic
      },
      ar: true,
      fr: true,
      cs: true,
      sv: true,
      en: false,
      "en-us": false,
      el: true
    };
  };

  return new depositRequirementsLocale();
});
