define([
  "ojL10n!lzn/beta/resources/nls/origination-generic"
], function(Generic) {
  "use strict";

  const orientationLocale = function() {
    return {
      root: {
        existingCustomer: "Already a customer banking online with us?",
        existingCustomerPayday: "Already a customer?",
        signInData: "Signing in with your login credentials will help us prefill some of the data",
        offerHead: "You are applying for",
        privacyAndSecurityPolicy: "private and secure.",
        whatThisMeans: "What this means for you",
        privacyInfo: "Model Bank keeps your personal information",
        impInfo: "Important Information About Opening a New Account",
        openAccountInfo: "Open your account today in just minutes with 3 easy steps",
        tellUs: "Tell us about yourself",
        setup: "Setup your account",
        reviewAndSub: "Review and Submit",
        getStarted: "Get Started",
        applyWithUs: "Apply in 5 minutes or less with our easy and secure application. Get a same-day credit decision.",
        beforeYouBegin: "Before You Begin",
        personalRequirements: "Personal Requirements",
        personalRequirements1: "You must be 18 or over (19 if you're in Alabama or Nebraska) and either a U.S. citizen or a resident alien (permanent or non-permanent) to apply for a car loan.",
        personalRequirements2: "You must Authorize the bank and or a credit bureau to investigate the information on the application.",
        youWillNeed: "You Will Need",
        youWillNeed1: "Social Security Number",
        youWillNeed2: "Driver's License, State ID or Military ID for each applicant",
        youWillNeed3: "Year, make and model of vehicle",
        youWillNeed4: "Estimated value",
        purchasingCarRequirement: "The car you're purchasing should",
        purchasingCarRequirement1: "Have fewer than 125,000 miles on it",
        purchasingCarRequirement2: "Have a clean title (no salvaged, rebuilt or brand-titled cars)",
        carShouldntBe: "And your car shouldn't be",
        carShouldntBe1: "Valued Less than $5000",
        carShouldntBe2: "More than 10 calendar years old",
        carShouldntBe3: "Commercial or used for commercial/business purposes",
        carShouldntBe4: "A grey market car",
        applyForPayday: "Apply for a Payday Loan with us in just a few minutes",
        whatWeRequire: "We will require the following information from you :",
        whatWeRequire1: "Your personal information including identity proof and contact information",
        whatWeRequire2: "Your employment and income information",
        whatWeRequire3: "Your loan requirements",
        checkYourEligibility: "Check your eligibility",
        checkYourEligibilityPaydayText: "You will need to fulfill the following eligibility criteria :",
        checkYourEligibility1: "You must be a legal major",
        checkYourEligibility2: "A USA citizen or resident alien",
        checkYourEligibility3: "Earn a regular income",
        checkYourEligibility4: "Have an active savings or checking account",
        whatUNeed: "What you'll need",
        startApplication: "Start Application",
        whatUNeed1: "Social Security Number of all applicants.",
        whatUNeed2: "Valid ID (Drivers License, State ID, Matricular Consular Card).",
        whatUNeed3: "Phone numbers and email addresses of all applicants.",
        whatUNeed4: "Physical U.S. address (no post office boxes).",
        whatUNeed5: "Debit/Credit Card or account information to fund your account.",
        whatUNeedLoanText: "The following details of all applicants",
        whatUNeedLoan1: "Personal and Contact details.",
        whatUNeedLoan2: "Employment and Income details.",
        whatUNeedLoan3: "Financial details.",
        whatUNeedLoan4: "Details of Vehicle being purchased.",
        accountInfo1: "We will ask you for basic information such as name, address, identity proof, etc.",
        accountInfo2: "You can specify your account preferences and fund your account.",
        accountInfo3: "Once your application is complete, review your data entered and submit the application.",
        privacyAndSecurityPolicyText: "We will not sell, distribute or lease your personal information to third parties unless we have your permission or are required by law. We may use your personal information to send you promotional information about third parties which we think you may find interesting if you tell us that you wish this to happen. We are committed to ensuring that your information is secure. In order to prevent unauthorized access or disclosure we have put in place suitable physical, electronic and managerial procedures to safeguard and secure the information we collect online.",
        whatThisMeansText: "When you open an account, we ask for your name, address, date of birth, and other information that will allow us to identify you. We may also ask to see your drivers license or other identifying documents.",
        patriotAct: "To help the government fight the funding of terrorism and money laundering activities, Federal law requires all financial institutions to obtain, verify, and record information that identifies each person who opens an account.",
        emailRequirementText: "We need your valid email address so we can communicate important information to you regarding your application.",
        SSNtext: "We need your Social Security Number to verify your identity and to acquire credit history to process your application.",
        previousAddressRequiredText: "To properly verify your identity, we need details of all addresses that you have resided in for the past two years.",
        priSec: "All your details are",
        termAccountInfo2: "You can setup your deposit and fund your account.",
        beforeYouApply: "Before You Apply",
        privacyAndSecurityClick: "Click For Privacy & Security",
        privacyAndSecurityClickInfo: "Click For Privacy & Security Info",
        checkYourEligibilityCardText: "In order to apply for a Model Bank Credit Card, you must be a legal major, a resident of the country and earn a regular income.",
        beforeYouApplyCardText: "Applying for a Model Bank Credit Card is easy. Your application should only take a few minutes but if you don't have enough time to complete your application now, you can save it and complete it at a later date.",
        beforeYouApplyText: "Applying for a Model Bank Personal Loan is easy. Your application should only take a few minutes but if you don't have enough time to complete your application now, you can save it and complete it at a later date.",
        checkYourEligibilityText: "In order to apply for a Model Bank Personal Loan, you must be a legal major, a resident of the country and earn a regular income.",
        userEmailRequirement: "Your Email address is required to register online. You will be able to use our online services by entering your email address as login ID and the password you specify while registering.",
        newToModelBank: "New to Model bank?",
        loginWithSocialMedia: "Login with social media",
        alreadyACustomerText: "It's faster to apply if you are an existing customer because we already have your information",
        continueAsGuest: "Continue as Guest",
        generic: Generic
      },
      ar: true,
      fr: true,
      cs: true,
      sv: true,
      en: false,
      "en-us": false,
      el: true
    };
  };

  return new orientationLocale();
});
