define(["ojL10n!resources/nls/generic", "ojL10n!resources/nls/register-biller-error", "ojL10n!resources/nls/payments-common"], function(Generic, RegisterBillerError, Common) {
  "use strict";

  const RegisterBillerLocale = function() {
    return {
      root: {
        generic: Generic,
        registerBillerError: RegisterBillerError,
        common: Common.payments.common,
        heading: {
          addBiller: "Add Biller",
          bills: "Bills",
          manageBillers: "Manage Billers",
          billerDetails: "Biller Details",
          deleteBiller: "Delete Biller",
          updteBiller: "Manage Biller",
          payBills: "Pay Bill"

        },
        labels: {
          CASA: "Account",
          CREDITCARD: "Credit Cards",
          DEBITCARD: "Debit Cards",
          sampleBill: "Sample Bill",
          sampleBillImage: "Sample Bill Image",
          viewSampleBill: "View Sample Bill",
          paymentMethod: "Payment Method",
          paymentType: "Payment Type",
          selectBiller: "Select Biller",
          billerCategory: "Category",
          selectCategory: "Select Category",
          billerLocation: "Location",
          billerName: "Biller Name",
          billNumber: "Bill Number",
          billPeriod: "Bill Period",
          billDate: "Bill Date",
          billDueDate: "Bill Due Date",
          billerType: "Biller Type",
          billerNickname: "Biller Nickname",
          billerNicknameInfo: "(Nickname should be unique)",
          billerLabel1: "Biller Label 1",
          customerName: "Customer Name",
          customerNameInfo: "(As mentioned in biller's record)",
          autoPay: "Auto Pay",
          paymentDate: "Payment Date",
          scheduledPay: "Scheduled Pay",
          detailedBill: "Detailed Bill",
          frequency: "Frequency",
          selectDate: "Select Date",
          startDate: "Start Date",
          endDate: "End Date",
          selectFrequency: "Select Frequency",
          scheduledDate: "Scheduled Date",
          frequencyType: "Frequency Type",
          ONE_TIME: "One Time",
          DAILY: "Daily",
          WEEKLY: "Weekly",
          FORTNIGHTLY: "Fortnightly",
          MONTHLY: "Monthly",
          QUARTERLY: "Quarterly",
          YEARLY: "Yearly",
          RECURRING: "Recurring",
          BIMONTHLY: "B-Monthly",
          SEMIANNUALLY: "Semi-Annually",
          billerAccount: "Pay From",
          yes: "Yes",
          no: "No",
          pay: "Pay",
          billAmount: "Bill Amount",
          limitAmount: "Limit Amount",
          viewBills: "View Bills",
          quickBillPay: "Quick Bill Pay",
          paymentHistory: "Payment History",
          billAmountRemark: "Entire amount will be paid for the bills presented",
          limitAmountRemark: "Auto pay will not be attempted for more than amount mentioned",
          amount: "Amount",
          registerBiller: "Add Biller",
          setAutoPay: "Set Auto Pay",
          paymentAmount: "Payment Amount",
          payNow: "Now",
          payLater: "Later",
          paidTo: "Paid To",
          paidFrom: "Paid From",
          expiryDate: "Expiry Date",
          selectStartDate: "Start Date",
          selectEndDate: "End Date",
          rechargeAmount: "Recharge Amount",
          selectPlan: "Select Plan",
          payWhen: "Pay When",
          debitMessage: "No Debit cards available",
          creditMessage: "No Credit cards available",
          location: "{location}",
          earlyPayDate: "Early Pay Date"

        },
        billerType: {
          PRESENTMENT_PAYMENT: "Presentment and Payment",
          PRESENTMENT: "Presentment",
          PAYMENT: "Payment",
          RECHARGE: "Recharge"
        },
        messages: {
          noBillerRegistered: "Currently you do not have any billers registered . Please go to Add Billers to register.",
          noBillersMapped: "Currently no billers are available under the selected category",
          paymentSupported: "Note: This biller accepts payment via {paymentTypes}",
          deleteBiller: "Are you sure you want to delete this biller?",
          addSuccessMessage: "Biller added successfully.",
          deleteSuccessMessage: "Biller deleted successfully.",
          updateSuccessMessage: "Biller updated successfully.",
          pendingApproval: "Pending Approval",
          sucessfull: "Successful",
          corpMaker: "You have successfully initiated the transaction.",
          cancelOperation: "Are you sure you want to cancel the operation?",
          reviewMsg: "You initiated a request for add biller. Please review details before you confirm!",
          reviewUpdateMsg: "You initiated a request for update biller. Please review details before you confirm!",
          reviewPaymentMsg: "You initiated a request for bill payment. Please review details before you confirm!",
          paymentSuccessMessage: "Payment done successfully !",
          review : "Review",
          somethingWentWrong:"Something went wrong.",
          checkProvidedDetails:"Check provided details."
        }
      },
      ar: false,
      en: false,
es :true,
      "en-us": false
    };
  };

  return new RegisterBillerLocale();
});
